version: 1
author: MD87
language: Go
image: golang:1.21
code: /code
workdir: /code
runonce: go install -buildvcs=false ./%dayzero%
cmd: %dayzero%
persistence:
  - /go/bin
  - /root/.cache/go-build
daypath: %zeroday%
inputfile: %zeroday%/input.txt
answerfile: %zeroday%/answers.txt
